### PR TITLE
Feature to development

### PR DESCRIPTION
**Pull request by Daniduran-dev**
This is the 4th time that I try to do a valid project because I had problems before with the linters not even running. I still need to do more things in the project and I also can't access my pathwright due to microverse technology issues, feel free to tell me the requirements since I can't get them.

### CODE REVIEW

**Comment by jubaan** [comment]
@Daniduran-dev Please email student success and tell them about your situation. The email is success@microverse.org. Use the word URGENT with uppercase in the subject. This way you'll gain access to the project description.

**Comment by Daniduran-dev** [comment]
Someone help me with this linter. I follow all the steps and its not working. I think it's in your side guys.

**Comment by jubaan** [comment]
@Daniduran-dev please be more specific, and instead of submitting the project reach a Full Time TSE they can assist you [TSE Meeting](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-CRs-TSEs-)

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @Daniduran-dev  ! :wave: :wave:

#### You have done well so far, your project works as expected :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.

**Recommended**
- [x]  The project should have a descriptive README.md .([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by Daniduran-dev** [comment]
- Added README.md

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  -   The app is functional 💯

- ### To Improve
  - [x] [Optional] Some of your commits are not good. ex: `readme done` 
  - [x] [Optional] Correct MIT link from your readme.

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
